#Sean Cork & Ian Squiers
#this a relatively simple python client that support XMLRPC servers.
#it works by interacting witha Front End server that appropriatly handles the
#requests generated by the client


#Import xmprpc
import xmlrpclib, sys


#THis function runs the client interatction. This fucntion connects this
#program to the Fron End server that then ahmdles all the requests generated by the client
#progam. 
def main():

	#Ask for the front end server
	if len(sys.argv) != 2:
	    print "Usage: [server]"
	    sys.exit()


	#sets hostname as server name
	hostname = sys.argv[1]
	x = 1
	y = 2

	name = "http://" + hostname + ":8124"
	server = xmlrpclib.Server(name)
	#have to give parameters to get welcome to work.
	welcome_reply = server.Front.welcome(x, y)
	#print a welcome for the client
	print(str(welcome_reply))


	#loop that takes request from the client.
	while(True):
		#client messages.
		request = raw_input("Here are the available actions\nsearch topic\nlookup item_number\nbuy item_number\nWhat would you like to do?\n")
		args = request.split(" ", 1)
		reply = server.Front.HandleRequest(args[0], args[1])
		print(reply)

	
main()